### ISSUE TITLE
Make parser more robust against changes in the output of `rustc`

### ISSUE THREAD

**Issue by Kimundi** [Kimundi/rustc-version-rs#11]
Right now the parser of `rustc`s version information is relatively strict, expecting a clearly defined format of lines.

However, seeing how `rustc` is unlikely to break its output in a backwards-incompatible way, but might add additional fields (as has already happened in the past), it might be more forward-compatible to just look for the `"<key>: <value>"` lines this crate knows about and silently ignore the rest.

**Comment by alexcrichton** [comment]
FWIW this caused [this change in rustc output](https://github.com/rust-lang/rust/pull/52052) to bounce in the past
