### ISSUE TITLE
Implement std::fmt::Display for Version and VersionMeta types

### ISSUE THREAD

**Issue by mcandre** [Kimundi/rustc-version-rs#14]
Please add a basic to-string method for the Version and VersionMeta structs, so that these can be easily printed to the terminal, without requiring potentially erroneous user code.

**Comment by Kimundi** [comment]
`Version` comes from semver, so its outside the control of this crate.

`VersionMeta` has a  `Debug` impl already - is that not enough?

**Comment by djc** [comment]
Going to close this for now. Feel free to reopen if this is still an issue.
