### ISSUE TITLE
Handle failing `rustc` invocations better

### ISSUE THREAD

**Issue by Kimundi** [Kimundi/rustc-version-rs#21]
From #18:

> Actually, I think it is an edge case, for possible improvement. In my environment, rustup and rustc are installed. But unfortunately (because some env vars were wrong) rustc seemed to invoke rustup which failed to create a lock file in a read-only directory. So the command did execute (i.e. start) but returned result "failed" and the output was not a valid version string. Maybe rustc_version should also check the success value from the command. In other words, add an error enum "command ran but failed."

**Comment by djc** [comment]
I think this was fixed in f894cc4cb13f44507685ca7c0b08ad0c33283771 (released as v0.3.2).
