### ISSUE TITLE
Consider recommending autocfg

### ISSUE THREAD

**Issue by matklad** [Kimundi/rustc-version-rs#28]
`autocfg` is a new-ish crate in the space of compiler version detection:

https://crates.io/crates/autocfg/

it's main difference is that it focuses on feature detection (rather then version detection) by default. For this reason, I would generally recommend using autocfg rather than rustc_version. If maintainers of rustc_version think that way, perhaps it makes sense to point towards this crate from readme?

**Comment by djc** [comment]
I've added a mention to the README, thanks for the suggestion!
