### ISSUE TITLE
version_meta fails with LlvmVersionError(TooManyComponents) on Rust Nightly

### ISSUE THREAD

**Issue by as-com** [Kimundi/rustc-version-rs#37]
This is the part that is failing: [https://github.com/Kimundi/rustc-version-rs/blob/a4bbdafb0b852f7e89e6ca9a69ae96f463301bcc/src/lib.rs#L139](https://github.com/Kimundi/rustc-version-rs/blob/a4bbdafb0b852f7e89e6ca9a69ae96f463301bcc/src/lib.rs#L139)

Output of `rustc -vV`:

```
rustc 1.51.0-nightly (4253153db 2021-01-17)
binary: rustc
commit-hash: 4253153db205251f72ea4493687a31e04a2a8ca0
commit-date: 2021-01-17
host: x86_64-pc-windows-msvc
release: 1.51.0-nightly
LLVM version: 11.0.1
```

**Comment by djc** [comment]
Thanks for the report, and sorry for breaking your code! I've released the fix as 0.3.3. For compatibility reasons, the LLVM micro version is not yet exposed in the API, I might revisit that in a future 0.4 release.
