### ISSUE TITLE
Add a changelog?

### ISSUE THREAD

**Issue by najamelan** [Kimundi/rustc-version-rs#42]
Hi, 

please consider adding a [changelog](https://keepachangelog.com/en/1.0.0/) to the project. Seeing version bumps from 0.2 -> 0.3 -> 0.4 makes me wonder what the breaking changes are, but it's not quite clear from the commit log. 

I think many people's first reaction when having to manually bump a version in `Cargo.toml` is to check for a changelog to see what upgrading implies.

**Comment by djc** [comment]
I added some changelogs for the releases I published, and will try to keep doing so in the future.
