### ISSUE TITLE
Do not use serde's std feature by default?

### ISSUE THREAD

**Issue by cr1901** [Kimundi/rustc-version-rs#43]
I can do this myself in a couple of days, but I've made a [workspace](https://github.com/cr1901/postcard-infomem) of crates for storing compiler metadata onto microcontroller flash.

The "data structures only" crate in the workspace is nominally `no_std` and no alloc. This way, a microcontroller environment can query the metadata if it so chooses.

However, thanks to feature union, this dependency enables `serde`'s std features and causes compilation to fail:

```sh
cargo +nightly build -p postcard-infomem-examples --target=msp430-none-elf --features=msp430g2553 -Zbuild-std=core
   Compiling semver v1.0.16
   Compiling postcard v1.0.2
   Compiling postcard-infomem-examples v0.1.0 (C:\msys64\home\William\Projects\rust-embedded\postcard-infomem\examples)
error[E0463]: can't find crate for `std`
```

```
PS C:\msys64\home\William\Projects\rust-embedded\postcard-infomem> cargo tree
postcard-infomem v0.1.0 (C:\msys64\home\William\Projects\rust-embedded\postcard-infomem)
├── postcard v1.0.2
│   ├── cobs v0.2.3
│   └── serde v1.0.152
│       └── serde_derive v1.0.152 (proc-macro)
│           ├── proc-macro2 v1.0.50
│           │   └── unicode-ident v1.0.6
│           ├── quote v1.0.23
│           │   └── proc-macro2 v1.0.50 (*)
│           └── syn v1.0.107
│               ├── proc-macro2 v1.0.50 (*)
│               ├── quote v1.0.23 (*)
│               └── unicode-ident v1.0.6
├── rustc_version v0.4.0
│   └── semver v1.0.16
│       └── serde v1.0.152 (*)
├── semver v1.0.16 (*)
├── serde v1.0.152 (*)
└── time v0.3.17
    ├── serde v1.0.152 (*)
    └── time-core v0.1.0
[dev-dependencies]
└── postcard v1.0.2 (*)
```

Is it possible to disable `serde`'s `std` feature and release a patch release so that my crate is usable in `no_std` environments?

**Comment by djc** [comment]
We can't drop serde's `std` feature in a semver-compatible release, because we'd expose fewer features for the same feature flags compared to before. Have you considered using the rustversion crate, instead?

**Comment by cr1901** [comment]
>because we'd expose fewer features for the same feature flags compared to before

Indeed, this is why I asked before starting a PR. At a glance, I couldn't see how `semver`'s `std` feature was used in the crate, but since you _wrote_ the crate (and the crate is small :D) you would know offhand.

>Have you considered using the rustversion crate, instead?

I need an actual `struct A` w/ version information so that I can populate another `struct B`. `version_meta` from this crate produces the `struct A`, and I don't believe I can make macros ergonomically populate a `struct B`.

That said, I believe I have a satisfactory workaround; I only _directly_ use the `Channel` type from `rustc_version` in my "data structures only" crate. I _already_ have to use `serde::with` to ser/deserialize it using my own `Channel` type since `Channel` doesn't derive `Serialize`/`Deserialize`. This way I can move `rustc_version` into the "crate where I assume `std` is available" to populate _my_ `struct`s.

It's not ideal- I wanted to reuse `rustc_version` for my `struct`s- but it's not that much extra code.

**Comment by cr1901** [comment]
I have worked around this locally using the workaround described in the previous message, so closing.
