### ISSUE TITLE
RUSTC_WRAPPER is ignored

### ISSUE THREAD

**Issue by RalfJung** [Kimundi/rustc-version-rs#45]
rustc-version has the same issue as https://github.com/rust-lang/cargo/issues/10885: it will by default ignore RUSTC_WRAPPER, so tools that expect to intercept all communication between a build and rustc by setting the wrapper will get entirely bypassed. If the wrapper ends up invoking an entirely different version of rustc than what is in the PATH, that can lead to incorrect results (e.g. when rustc-version is used from a build script).

**Comment by djc** [comment]
Happy to review a PR -- I'm doing passive maintenance only for this project.

**Comment by hkBst** [comment]
I think the only thing needed for this is that:

```rust
pub fn version_meta() -> Result<VersionMeta> {
    let cmd = env::var_os("RUSTC").unwrap_or_else(|| OsString::from("rustc"));

    VersionMeta::for_command(Command::new(cmd))
}
```

first checks RUSTC_WRAPPER, maybe like so:

```rust
pub fn version_meta() -> Result<VersionMeta> {
    let rustc = env::var_os("RUSTC").unwrap_or_else(|| OsString::from("rustc"));
    let cmd = if let Some(wrapper) = env::var_os("RUSTC_WRAPPER") {
        Command::new(wrapper).arg(rustc)
    } else {
        Command::new(rustc)
    };

    VersionMeta::for_command(cmd)
}
```

**Comment by djc** [comment]
@hkBst great -- want to submit a PR for that?

**Comment by hkBst** [comment]
done

**Comment by RalfJung** [comment]
This seems mostly right, except for one corner case: if the env var is set to the empty string, that means there is no wrapper.

**Comment by hkBst** [comment]
@RalfJung I've added flitering for empty strings, see #46.
