### ISSUE TITLE
Fails if `RUSTC` is a relative path

### ISSUE THREAD

**Issue by bluss** [Kimundi/rustc-version-rs#6]
Hi! I don't know if this is an actionable bug (feel free to close).

If RUSTC is a relative path, and rustc_version is used in a dependency, the build script will fail like this:

```
thread '<main>' panicked at 'failed to execute `RUSTC -vV`: No such file or directory (os error 2)'
```

**Comment by kamalmarhubi** [comment]
Does cargo change the working directory before calling build scripts?

If it's impossible to support relative paths, there could be an explicit check and a more informative error message.

**Comment by pantaloons** [comment]
It also fails if RUSTC is unspecified (not present), and "rustc" can't be found on the PATH, even though this is a valid install configuration.

I think it should probably check for RUSTC, and if that isn't found use the cargo executable dir + "rustc"

**Comment by Kimundi** [comment]
Hi, I'm [sincerely sorry for taking so long to respond.](https://gist.github.com/Kimundi/9b10629d29adbf163d8eb053ddaa1f38)

@bluss: Does this issue still happen with cargo? (I'm not sure how to check this correctly)
@pantaloons: Could you elaborate a bit? When I wrote the executable path lookup logic I mirrored what cargo did at that time, which was to use `RUSTC` or `rustc` from the path. Has this changed?

**Comment by bluss** [comment]
Yes it still fails the same way. One way to reproduce:

1. Add `debugit = "=0.1.0"` as a dependency, because it uses rustc_version (0.1.x though) in a build script
2. Put in a local link to rustc: `ln -s $(which rustc)`
3. RUSTC=./rustc cargo build

```
thread 'main' panicked at 'failed to execute `RUSTC -vV`: No such file or directory (os error 2)'

stack backtrace:
   0: rustc_version::version_meta::{{closure}}
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc_version-0.1.7/src/lib.rs:109
   1: <core::result::Result<T, E>>::unwrap_or_else
             at /checkout/src/libcore/result.rs:706
   2: rustc_version::version_meta
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc_version-0.1.7/src/lib.rs:106
   3: build_script_build::main
             at ./build.rs:12


rustc 1.17.0-nightly (b1e31766d 2017-03-03)
cargo 0.18.0-nightly (5db6d64 2017-03-03)

```

**Comment by bluss** [comment]
Note: This is not a bug that hits me anymore. I've put a script that runs my current build of rust nightly from git (when applicable) directly into my path instead.

**Comment by Kimundi** [comment]
Hm, tricky. As @kamalmarhubi said, this sounds like cargo might be at "fault" here by changing the current working directory. I'm not sure if this is fixable from this end.

**Comment by djc** [comment]
Going to close this for now. Feel free to reopen if there is still an issue here.
